pipeline {
    agent any

    environment {
        IMAGE_NAME = "enterprise-python-app"
        IMAGE_TAG = "v1"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'develop',
                url: 'https://github.com/sarthak24shirbhate/enterprise-devops-platform.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG app/python-app'
            }
        }

        stage('Container Validation') {
            steps {
                sh 'docker rm -f test-container || true'

                sh '''
                docker run -d \
                --name test-container \
                -p 5000:5000 \
                $IMAGE_NAME:$IMAGE_TAG
                '''

                sh 'sleep 5'

                sh 'docker ps'

                sh 'docker logs test-container'
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker rm -f test-container || true'
            }
        }
    }
}
