pipeline {
    agent any

    environment {
        IMAGE_NAME = "enterprise-python-app"
        IMAGE_TAG = "v1"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'develop',
                url: 'https://github.com/sarthak24shirbhate/enterprise-devops-platform.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG app/python-app'
            }
        }

        stage('Run Container Test') {
            steps {
                sh 'docker rm -f test-container || true'

                sh 'docker run -d --network host --name test-container $IMAGE_NAME:$IMAGE_TAG'

                sh 'sleep 10'

                sh 'curl http://localhost:5000'
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker rm -f test-container || true'
            }
        }
    }
}
